name: C02231

on:
  push:
    branches: [ "C02231" ]

jobs:
  unitTest:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: store
          MYSQL_USER: store
          MYSQL_PASSWORD: 123456
    steps:
    - uses: actions/checkout@v4
    - name: Wait for MySQL to be healthy
      run: |
        docker ps -a
        #docker-compose run --rm wait-for-it.sh mysql:3306 -t 30
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        cd C02231/Store/Lab7
        dotnet restore
    - name: Build
      run: |
        cd C02231/Store/Lab7
        dotnet build --no-restore
    - name: Test
      run: |
        cd C02231/Store/Lab7
        dotnet test --no-build --verbosity normal
  publish-Api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd  C02231/Store/Lab7
        docker image build -t lani06/storeapi:latest .
        docker image build -t lani06/storeapi:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC02231  }}" | docker login -u "pchavesr29@gmail.com" --password-stdin
        docker push lani06/storeapi:latest
        docker push lani06/storeapi:0.0.1
  publish-UI:   
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        cd  C02231/Store/React/nextjs-dashboard
        docker image build -t lani06/react:latest .
        docker image build -t lani06/react:0.0.1 .
        echo "${{ secrets.DOCKERHUBPASSC02231  }}" | docker login -u "pchavesr29@gmail.com" --password-stdin
        docker push lani06/react:latest
        docker push lani06/react:0.0.1    